publish_mode: editorial_workflow
media_folder: static/images/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /images/uploads # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          dateFormat: "DD.MM.YYYY",
          timeFormat: "HH:mm",
          format: "LLLL",
        }
      - {
          label: "Latest Update",
          name: "latestEdit",
          widget: "datetime",
          dateFormat: "DD.MM.YYYY",
          timeFormat: "HH:mm",
          format: "LLLL",
        }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blurb" # Used in routes, e.g., /admin/collections/blog
    label: "Blurb" # Used in the UI
    folder: "content/blurb" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    folder: "content/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Workplace", name: "workplace", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - {
          label: "Start Date",
          name: "start-date",
          widget: "datetime",
          dateFormat: "DD.MM.YYYY",
          timeFormat: false,
          format: "LLLL",
        }
      - {
          label: "End Date",
          name: "end-date",
          widget: "datetime",
          dateFormat: "DD.MM.YYYY",
          timeFormat: false,
          format: "LLLL",
        }
      - { label: "Body", name: "body", widget: "markdown" }
backend:
  name: git-gateway
  branch: master
